### PR TITLE
Add sum of expectation

### PR DESCRIPTION
**Pull request by Katalam**
When merge this will:
* add .idea folder to git ignore
* add a strict check to prime expectation
* add a sum of expectation

### CODE REVIEW

**Comment by faissaloux** [comment]
Hello @Katalam 

When I'll use `toBeSumOf()`, I'll expect to sum up the first argument like the other methods `toBePowerOf()` and `toBeFactorialOf()` ...

So to be consistent and not confusing, can you move the callable `$step` to the first position and make it able to accept an array as well, so it either sum up the array of numbers or the callable with `$from` to `$to` (Rename those params too please).

Thank you

**Comment by faissaloux** [comment]
I'm thinking about separate this to two methods:

- `toBeSumOf()` should accept only an array of numbers.
- Another one that accepts `$step`, `$from` and `$to` (This order should be respected) .

**Comment by faissaloux** [comment]
ping @Katalam

**Comment by Katalam** [comment]
I broke my forked git tree somehow, but I removed all the unwanted commit changes

**Comment by faissaloux** [comment]
@Katalam thanks for your contribution!

**Pull request merged**
